language: node_js
node_js: 10
install: npm install
script: 
  - npm test
  - npm run docs:build
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master