language: node_js
node_js: 10
install: npm install
script:
- npm test
- npm run docs:build
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/
  github_token: "$GITHUB_TOKEN"
  keep_history: true
  on:
    branch: master
env:
  global:
  - secure: TI/kLXMQm3k0EShN5jLuwMAsNVNnh3GAl4qSqqEsyP8pFN7cCi7iCDKQZBcBC/mqiUeybanKO24usQlfKSAtTy/20uFOcz40UN/2ZeJT11KznGdCCR8kfSgS5Lnm6ozM/+rpE58ZYSANnwHGF1tkqdHXqn9wC7X3NLWWgTtvnJ/Estlk01FbGt40MAAtEpwwLiUfC9ieF20x30baVCV+fn6EQtfhrWueywI8ijjaIx7VBFXEQj7XydeaYjQpfHzx10fbg1NotgRU8Hw1EoiAMwkC84dzalrXlknZmVjaJqLYS41MirlyqLyZMmDlfXlfY1aqUyPFFscbB0V91/B8vNCUAnX2pAky2gMlbfI3SSUadbj8SPVbRwceMf+2O1uNwBEDuDUAVjtGixatAEUCepfZWmwCQoxm92oiqTd+RVItCa6jkuGIoSrAe678imZz+s5cdq66IT6npbS4j9h3GPcIgTbwVP6ym3ACbTO4LxWF7gxZCG8hHdKxXXM/4uKbNkRsMZaUNdjxymM7223JgUW2MBcx+TsD71MINl2dSRGjsvUNYdVIyniAq7D5QavV14w23rRCWUkGWxAQ19Kojp4qPeGme6WrePhr2B3/Yxjf9ZG+5zPuTz+7T/7T0o/mE0VAuDVZpdIbC9Nd0wKhcngfi1kyOilWPMJyXkjZaUs=
