name: Lint
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Installation
      run: npm install
    - name: Lint
      run: npm run lint
